=== usrhub/ping_monitor/xml/device-config.dtd
<!ELEMENT config (device)*>
<!ELEMENT device (ip?, name?, interval?, limit?, maxgraph?, email?)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT interval (#PCDATA)>
<!ELEMENT limit (#PCDATA)>
<!ELEMENT maxgraph (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== usrhub/ping_monitor/xml/config.xml
<!DOCTYPE config SYSTEM "device-config.dtd">
<config>
	<device>
		<ip>127.0.0.1</ip>
		<name>Test machine</name>
		<interval>355</interval>
		<limit>37</limit>
		<maxgraph>500</maxgraph>
		<email>sadf</email>
	</device>
	<device>
		<ip>127.0.0.1</ip>
		<name>Test machine 2</name>
		<interval>355</interval>
		<limit>37</limit>
		<maxgraph>500</maxgraph>
		<email>sadf</email>
	</device>
	<device>
		<ip>127.0.0.1</ip>
		<name>Test machine 3</name>
		<interval>355</interval>
		<limit>37</limit>
		<maxgraph>500</maxgraph>
		<email>sadf</email>
	</device>
</config>
